[package]
name = "roomgame"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9"
bevy-inspector-egui = { version = "0.14", optional = true }
bevy_mod_picking = "0.10"
iyes_loopless = "0.9"
rand = "0.8"

[features]
inspector = ["dep:bevy-inspector-egui"]
