[package]
name = "roomgame"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8"
bevy-inspector-egui = { version = "0.13", optional = true }
bevy_mod_picking = "0.9"
iyes_loopless = "0.8"
rand = "0.8"

[features]
inspector = ["dep:bevy-inspector-egui"]
